### ISSUE TITLE
annotation pipeline (and CVR fetcher) notices failed records in response

### ISSUE THREAD

**Issue by sheridancbio** [genome-nexus/genome-nexus-annotation-pipeline#115]
After the response comes back from genome nexus, some records will have a failure status. These should be detected and logged / stripped out or otherwise treated properly.

**Comment by mandawilson** [comment]
- [ ] Update documentation genome-nexus-java-api-client/genomeNexusPublicApiClient/docs/VariantAnnotation.md
- [ ] Use swagger-codegen to update the client model genome-nexus-java-api-client/genomeNexusPublicApiClient/src/main/java/org/genome_nexus/client/VariantAnnotation.java

**Comment by averyniceday** [comment]
to generate new models using swagger-codegen
run the following script inside the java api:
https://github.com/genome-nexus/genome-nexus-java-api-client/blob/master/scripts/generateApiClientModules.sh

**HOWEVER**, update script to
- point to your own GN deployment (e.g localhost:38080... for new code)
- I had to redownload the swagger-codegen jar and replace the one checked into the repository. Running the script gave me a `Error: Invalid or corrupt jarfile swagger-codegen-cli.jar` error

**Comment by averyniceday** [comment]
PRs open in `pipelines` and `cmo-pipelines` - mostly removing duplicate code (e.g partitioning into chunks)

Waiting for further discussion regarding GN annotation pipeline before opening PR. Specifically, need to resolve issue of where `isFailedAnnotatedRecord()` check should be placed. Current behavior seems to prevent any Genome Nexus annotation from actually being used during POST.

**Comment by averyniceday** [comment]
Before merging PRs, GN-annotation pipeline must be migrated to front of master and unit tests updated. Hash will be regenerated and propagated to downstream clients.
