### ISSUE TITLE
Migrate GN Annotation Pipeline to Work with Genome Nexus Server Master

### ISSUE THREAD

**Issue by averyniceday** [genome-nexus/genome-nexus-annotation-pipeline#120]
- [x] Document and resolve differences in the model (verify that changes are okay, what data is lost or gained)
- [x] Get GN Annotation Pipeline to build (including unit tests) when using a genome nexus java api hash that is based on master (including newest changes with successfully_annotated flag)
- [x] document migration steps for future reference (as a readme checked in to docs)
- [x] regression tests show that the revised code with a master branch deployment of genome nexus produces comparable results to the current production pipeline.

**Comment by sheridancbio** [comment]
**Goal Set for 2020_02_26 standup : we will know the extent of the changes needed to massage the codebase (and unit tests) to use the new models**

**Comment by averyniceday** [comment]
Google Doc for documenting schema changes (so far I only included classes where something was actually removed/renamed - and I only documented what was dropped): https://docs.google.com/spreadsheets/d/1QnQdxVAQNxBkMQjXxvg1DA4lWdQzudSwgUAPB-uXZ2A/edit?usp=sharing

Also comparing hashes - pull my branch in `genome-nexus-java-api-client/testgn` and compare to `v1.1.0-beta` (the jitpack tag/hash used in`genome nexus annotation pipeline`)

**Comment by sheridancbio** [comment]
Scrum daily goal accomplished, although verification will be helpful

**Comment by sheridancbio** [comment]
**Goal Set for 2020_02_26 standup : we will have run the new genome nexus annotation pipeline code with a new genome nexus release with our server code changes. The observed output from running a substantial maf (mskimpact_2017 or a fraction) will be compared to the current production output to see if gross differences are present (dropped fields, missing values)

**Comment by sheridancbio** [comment]
The daily goal set for today was not met - the genie_private study import (thought to be needed for Monday) disrupted work on this goal. Instead, this goal is reset for the standup tomorrow

**Comment by sheridancbio** [comment]
Goal Set for 2020_03_03 standup : we will have run the new genome nexus annotation pipeline code with a new genome nexus release with our server code changes. The observed output from running a substantial maf (mskimpact_2017 or a fraction) will be compared to the current production output to see if gross differences are present (dropped fields, missing values)

**Comment by mandawilson** [comment]
- [ ] Make sure you clean up: kops delete ig genie-performance-test (name doesn't make sense)
