### ISSUE TITLE
options to add functional impact columns into MAF

### ISSUE THREAD

**Issue by jjgao** [genome-nexus/genome-nexus-annotation-pipeline#147]
- MutationAssessor
- SIFT
- PolyPhen-2

**Comment by ao508** [comment]
Do we know what fields are desired in the annotated MAF?

MA for example has a ton of information so I was wondering how many of these fields that are returned in the JSON should be added to an annotated MAF that the annotation pipeline generates. 

To start we can just make sure that we are getting these in the JSON response and figure out what columns to add to the annotated MAF later.

**Comment by ao508** [comment]
Mutation Assessor is already supported  ✔️

**Comment by ao508** [comment]
PR to server repo: https://github.com/genome-nexus/genome-nexus/pull/449
PR to Java api client repo: https://github.com/genome-nexus/genome-nexus-java-api-client/pull/8

PR to annotation pipeline [ REQUIRES ABOVE PRs TO BE MERGED FIRST ] : https://github.com/genome-nexus/genome-nexus-annotation-pipeline/pull/148 * will also require an additional update to get the commit hash from the master branch once the above PR is merged

**Comment by ao508** [comment]
@jjgao Following up on this - do we know what Mutation Assessor fields(s) we need to include in the output annotated MAF?

This is what we get in the JSON response from Genome Nexus for `mutation_assessor`

```
  "mutation_assessor": {
    "annotation": {
      "codonStartPosition": "string",
      "cosmicCount": 0,
      "functionalImpact": "string",
      "functionalImpactScore": 0,
      "hgvs": "string",
      "hugoSymbol": "string",
      "input": "string",
      "mappingIssue": "string",
      "msaGaps": 0,
      "msaHeight": 0,
      "msaLink": "string",
      "pdbLink": "string",
      "referenceGenomeVariant": "string",
      "referenceGenomeVariantType": "string",
      "refseqId": "string",
      "refseqPosition": 0,
      "refseqResidue": "string",
      "snpCount": 0,
      "uniprotId": "string",
      "uniprotPosition": 0,
      "uniprotResidue": "string",
      "variant": "string",
      "variantConservationScore": 0,
      "variantSpecificityScore": 0
    },
    "license": "string"
  }
```

**Comment by ritikakundra** [comment]
@ao508 : For the MAF I need, we would like to see what is shown in the portal:
<img width="181" alt="Screen Shot 2020-09-24 at 11 34 30 AM" src="https://user-images.githubusercontent.com/12007862/94167394-7617bb80-fe5a-11ea-8c52-45cd6127cb56.png">
<img width="145" alt="Screen Shot 2020-09-24 at 11 34 25 AM" src="https://user-images.githubusercontent.com/12007862/94167397-76b05200-fe5a-11ea-9b1c-8e8713de0793.png">
<img width="248" alt="Screen Shot 2020-09-24 at 11 34 19 AM" src="https://user-images.githubusercontent.com/12007862/94167398-76b05200-fe5a-11ea-94e7-d34109a795de.png">

**Comment by ao508** [comment]
@ritikakundra Here is how I plan on naming the columns:

- Polyphen_Prediction
- Polyphen_Score
- SIFT_Prediction
- SIFT_Score
- MA:FImpact
- MA:FIS <-- functional impact score value


The reason for the different naming convention for the MA fields is to match the field names that the importer expects: https://github.com/cBioPortal/cbioportal/blob/master/core/src/main/java/org/mskcc/cbio/portal/scripts/ImportExtendedMutationData.java#L220

**Comment by sheridancbio** [comment]
There is follow up work on this card in order for it to be usable. A new genome nexus server needs to be built and deployed for the three genome nexus deployments (public, genie, annotation)

**Comment by jjgao** [comment]
@ao508 maybe change "MA:FImpact" to "MA_Prediction" and "MA:FIS" to "MA_Score" to be consistent?

**Comment by ao508** [comment]
I used “MA:*” to be consistent with the importer code (see the MafRecord parser class in the cbioportal core)
