### ISSUE TITLE
Error runnnig docker on v1.0.0

### ISSUE THREAD

**Issue by aclosa** [genome-nexus/genome-nexus-annotation-pipeline#258]
Hi, 
I am having troubles to run the new docker version. 

docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: exec: "--filename": executable file not found in $PATH: unknown.

This error was not present in the previous version of the docker image. Also I was comparing both docker image version and the size is different.

Could you please check the new docker image?

Thanks

**Comment by aclosa** [comment]
I found the problem.
You have change from ENTRYPOINT to CMD in the Docker file but the README file still explain how to run the old method.
Would it be possible to update the README file?

**Comment by aclosa** [comment]
Solve it running 

"docker run -v ${PWD}:/wd genomenexus/gn-annotation-pipeline:master java -jar /genome-nexus-annotation-pipeline/annotationPipeline/target/annotationPipeline.jar --filename /wd/input.txt  --output-filename /wd/output.txt"

**Comment by inodb** [comment]
@aclosa we just reverted this change back after several users pointed out the docs were incorrect
