### ISSUE TITLE
application.properties.EXAMPLE base url

### ISSUE THREAD

**Issue by jjgao** [genome-nexus/genome-nexus-annotation-pipeline#66]
Currently, in [application.properties.EXAMPLE](https://github.com/genome-nexus/genome-nexus-annotation-pipeline/blob/master/annotationPipeline/src/main/resources/application.properties.EXAMPLE#L2), genomenexus.base=<HOST> is not specified. Maybe we can just add the public genome nexus address here?

**Comment by ao508** [comment]
resolved
