### ISSUE TITLE
turn on replace-symbol-entrez by default

### ISSUE THREAD

**Issue by jjgao** [genome-nexus/genome-nexus-annotation-pipeline#69]
Should we consider turning on `replace-symbol-entrez` by default? The symbols should be synchronized with the annotated results.

https://github.com/genome-nexus/genome-nexus-annotation-pipeline/blob/master/annotationPipeline/src/main/java/org/cbioportal/annotation/AnnotationPipeline.java#L59

@n1zea144 @inodb @onursumer

**Comment by jjgao** [comment]
@n1zea144 @angelicaochoa are you setting `replace-symbol-entrez` to true in the pipeline? OK if we switch to true as default?

**Comment by angelicaochoa** [comment]
@jjgao no it is not set to true by default. we can start though

**Comment by jjgao** [comment]
@angelicaochoa I think we should turn it on to remove potential data issues and it'll also fill all entrez gene IDs. I don't think it'll hurt.

Could you make a pull request to turn it on by default (https://github.com/genome-nexus/genome-nexus-annotation-pipeline/blob/master/annotationPipeline/src/main/java/org/cbioportal/annotation/AnnotationPipeline.java#L59) and make sure it's working in the pipeline? Thanks.

**Comment by angelicaochoa** [comment]
@jjgao only drawback is that the annotation pipeline will take longer to run. The entrez id ---> hugo symbol mapping is stored in memory. We did not want to store these mappings in mongo since NCBI performs updates to the mapped hugo symbols fairly regularly. 

I'll make a PR for our importer and internal cohort pipelines to replace the symbols by default but I'm thinking that the standalone GN annotation pipeline should be left as is. @n1zea144 comments?

**Comment by jjgao** [comment]
@angelicaochoa I logged an mis-annotated mutation in the public portal that is related to this: https://github.com/cBioPortal/datahub/issues/262. I think we should turn on "replace symbols and entrez" by default soon. Could you also comment on how the mapping was maintained?

**Comment by angelicaochoa** [comment]
@jjgao The mapping is done based on the ENSEMBL REST API https://rest.ensembl.org/documentation/info/xref_id

The ENSEMBL gene accession from the annotated variant is used to map to the Entrez gene ID and Hugo Symbol http://annotation.genomenexus.org/swagger-ui.html#!/ensembl45controller/fetchGeneXrefsGET

**Comment by angelicaochoa** [comment]
@jjgao I've made PR's for replacing/updating hugo symbol and entrez gene id by default:

https://github.com/knowledgesystems/cmo-pipelines/pull/399
https://github.com/knowledgesystems/pipelines/pull/340

**Comment by jjgao** [comment]
Thanks, @angelicaochoa. Would it make sense to change to true here too? https://github.com/genome-nexus/genome-nexus-annotation-pipeline/blob/master/annotationPipeline/src/main/java/org/cbioportal/annotation/AnnotationPipeline.java#L59

**Comment by jjgao** [comment]
@inodb do we have a web api to map ENSG to Hugo_Symbol and Entrez_Id? Ideally we should have a fixed mapping file that we can update periodically (manually).

**Comment by inodb** [comment]
@jjgao not to entrez id but we do have an ep to map to Hugo symbol. E.g.  https://www.genomenexus.org/swagger-ui.html#!/ensembl45controller/fetchCanonicalEnsemblGeneIdByHugoSymbolGET. This maps all Hugo symbols to a canonical ensg. We could add entrez id as well

**Comment by jjgao** [comment]
@inodb can we also get the entrez id? We could store the [hugo gene file](ftp://ftp.ebi.ac.uk/pub/databases/genenames/new/tsv/hgnc_complete_set.txt) locally.

**Comment by inodb** [comment]
@jjgao @angelicaochoa Thought about this a bit more - I think we should actually get the hugo symbol from the annotation instead of independently replacing entrez ids. Cause it might well be that the entrez id is completely off. It's more important that the annotation matches the hugo symbol

**Comment by angelicaochoa** [comment]
@inodb @jjgao the flow for replacing gene ids:

1. get ensembl gene id from canonical transcript 

[17:g.41242962_41242963insGA](http://annotation.genomenexus.org/annotation/17%3Ag.41242962_41242963insGA?isoformOverrideSource=uniprot&fields=hotspots%2Cmutation_assessor) --> ENSG00000012048

2. get xrefs for ensembl gene id 

[ENSG00000012048](http://annotation.genomenexus.org/ensembl/xrefs?accession=ENSG00000012048)

3. find external references where dbName is "EntrezGene" 
Note: many types of references from various databases, sometimes multiple objects where db name is "EntrezGene" but the description may be "pseudogene" or "uncharacterized". This example only has one object in json where dbname is "EntrezGene" though. If more than one record is dbName "EntrezGene" and the description is not "pseudogene" or "uncharacterized" then use first in list for `TranscriptConsequenceSummary`.

Based on this it's my understanding then that we already are using the appropriate entrez gene id when replacing/updating whatever is in the maf. The VEP JSON returns HGNC ID, which is different from Entrez and unused by Genome Nexus. 

The only time I see an entrez gene id in the VEP JSON returned is when [the `annotationSummary` param is used](http://annotation.genomenexus.org/annotation/17%3Ag.41242962_41242963insGA?isoformOverrideSource=uniprot&fields=hotspots%2Cmutation_assessor%2Cannotation_summary
), which we also don't use in our pipelines.  

As far as the actual hugo symbol goes - are there really any discrepancies between the hugo symbol returned in the VEP JSON vs. the external references? The hugo symbol linked to ensembl gene id `ENSG*` should not be discrepant between what's in the VEP JSON and what's returned from the call to the gene external references. 

The only thing I can really think of suggesting is perhaps attempting to match on ""gene_symbol" from the VEP JSON and "display_id" from the xrefs JSON if more than one xref has dbName = "EntrezGene" and description != "pseudogene" or "uncharacterized". Does this idea make sense? Sorry if it isn't explained well.

**Comment by jjgao** [comment]
It looks like the tmb_mskcc_2018 MAF has both KMT2C and MLL3 (KMT2C alias), even though it was reannotated. That's another reason we should always turn on `replace-symbol-entrez`.

We should probably also reannotating the mskimpact MAF when there is a change in gene symbols.

cc'ing @n1zea144 @ritika
